### ISSUE TITLE
Build Failure - Carthage

### ISSUE THREAD

**Issue by wm-j-ray** [DenHeadless/DTModelStorage#12]
Greetings,

I am trying to run DTTableViewManager and I get a carthage build error on DTModelStore related to Realm and Realm Swift.  I have attached the terminal output which also hits some depreciations.  I tried building using the project but couldn't get it to compile.

Also, If I am not planning on using Realm, is there anyway that it can be eliminated from the framework?

Thanx a lot -- DTTableViewManager looks amazing and I can't wait to try it in a project I'm working on.

![screen shot 2016-05-27 at 3 26 25 pm](https://cloud.githubusercontent.com/assets/770852/15619029/8507af16-241f-11e6-9284-bc293f50f572.png)

**Comment by DenHeadless** [comment]
Hey!

It seems like you are trying to build very old version of DTTableViewManager. It was converted to Swift 2 ages ago. Please try using latest version

Carthage:
```ruby
github "DenHeadless/DTTableViewManager" ~> 4.7.0
```

CocoaPods:
```ruby
pod 'DTTableViewManager', '~> 4.7.0'
```

**Comment by wm-j-ray** [comment]
How about Realm? Should that be in my cartfile or can I leave it out.

**Comment by DenHeadless** [comment]
If you use Carthage, than you can leave it out, since it's automatically installed as a dependency to `DTModelStorage`.

If you use CocoaPods, you can use pod 'DTModelStorage/Realm' to include Realm.framework.
