### ISSUE TITLE
Can you support swift3?

### ISSUE THREAD

**Issue by Sweeper777** [DenHeadless/DTModelStorage#13]
I just updated to Swift 3, and converted the syntax. However, I found there's these errors in the DTModelStorage module:

<img width="236" alt="screen shot 2016-09-28 at 7 31 51 am" src="https://cloud.githubusercontent.com/assets/13585047/18902868/a60bc424-854d-11e6-96f4-cc8ac6a10b4f.png">

**Comment by DenHeadless** [comment]
Swift 3 is already supported, please use 3.0.0-beta-2 version or higher - we'll make a final release somewhere in October.

**Comment by DenHeadless** [comment]
And if you use DTTableViewManager or DTCollectionViewManager, use `5.0.0-beta.2` and higher.

**Comment by Sweeper777** [comment]
Can you show me what should I write in `Podfile` to install a certain branch of the pod?

**Comment by DenHeadless** [comment]
```ruby
pod 'DTModelStorage', '~> 3.0.0-beta.2'
pod 'DTTableViewManager', '~> 5.0.0-beta.2'
```

**Comment by Sweeper777** [comment]
Thank you!
