### ISSUE TITLE
RealmStorage - have you considered support for List?

### ISSUE THREAD

**Issue by skydivedan** [DenHeadless/DTModelStorage#16]
In Realm, both `Results` and `List` support the `RealmCollection` protocol. That protocol contains the `addNotificationBlock` declaration.

So, instead of passing in a `Results<T>` to `RealmSection` and `RealmStorage`, you could pass in `AnyRealmCollection<T>` instead.

**Comment by DenHeadless** [comment]
Hey!

I did not see those actually, i will take a look at it. Or, you can drop a PR with this, if you need it right now.

**Comment by skydivedan** [comment]
Glad to help. Unfortunately, I can't get to this right away. Probably won't be able to circle back until *maybe* next week. But if you haven't gotten to it by the time I can look at it again, I'll be happy to write some code and submit a PR.

**Comment by DenHeadless** [comment]
Sure, there's no rush to do this right now. Keep in touch.

**Comment by skydivedan** [comment]
Hey there, I think I have a solution. I've tried it in a sample app with a list, but I haven't added the code to the tests yet. But I should be making a PR soon.

**Comment by skydivedan** [comment]
How long until you rev the podspec?

**Comment by DenHeadless** [comment]
Probably today or tomorrow - I wanted to verify that everything works in XCode 8 and Xcode 9 beta 1 before making a release.

**Comment by DenHeadless** [comment]
Seems everything's fine, i've made a new release:
https://github.com/DenHeadless/DTModelStorage/releases/tag/5.1.0

🍺
