### ISSUE TITLE
Use of undeclared type 'AnomalyHandler'

### ISSUE THREAD

**Issue by makleso6** [DenHeadless/DTModelStorage#26]
can not build
`open class MemoryStorageAnomalyHandler : AnomalyHandler { //Use of undeclared type 'AnomalyHandler'
`

**Comment by DenHeadless** [comment]
Hi!
Please give more information, what version are you using? Whas Swift compiler version you have?

**Comment by makleso6** [comment]
latest version 7.1.0
Xcode Version 9.4.1

**Comment by DenHeadless** [comment]
Well, there's not enough information to continue any investigation. I believe that if you don't see this class, you have a Swift version lower than 4.1, which is required for it, but I have CI jobs that check that project compiles using Swift 4.1 as well as Swift 3.2/Swift 3.3 versions.

So i have no ideas why project does not compile on your side.

**Comment by makleso6** [comment]
Try to create empty project with Podfile, and you will see error
